FROM ubuntu:xenial
MAINTAINER Bytten Studio "bytten.games@gmail.com"
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["lead.py","5001"]
